// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-Rfih72jpYdexxJSCCpWyVwIeci8-7k',
    appId: '1:736732329341:web:30f77dc0314fa707028814',
    messagingSenderId: '736732329341',
    projectId: 'pixel-bot-cc860',
    authDomain: 'pixel-bot-cc860.firebaseapp.com',
    storageBucket: 'pixel-bot-cc860.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvaWshof-rEbZUYj0J8gj-j1HQbfCecvw',
    appId: '1:736732329341:android:b34f5661e122764e028814',
    messagingSenderId: '736732329341',
    projectId: 'pixel-bot-cc860',
    storageBucket: 'pixel-bot-cc860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwAqkWf1r5y2sa9WYrj-jEnqlt7eWSWs8',
    appId: '1:736732329341:ios:8aa4af4e49e93e85028814',
    messagingSenderId: '736732329341',
    projectId: 'pixel-bot-cc860',
    storageBucket: 'pixel-bot-cc860.firebasestorage.app',
    iosClientId: '736732329341-c2hul7rfjkej9gn7eh47f7ng321ksc6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.visioniq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwAqkWf1r5y2sa9WYrj-jEnqlt7eWSWs8',
    appId: '1:736732329341:ios:8aa4af4e49e93e85028814',
    messagingSenderId: '736732329341',
    projectId: 'pixel-bot-cc860',
    storageBucket: 'pixel-bot-cc860.firebasestorage.app',
    iosClientId: '736732329341-c2hul7rfjkej9gn7eh47f7ng321ksc6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.visioniq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-Rfih72jpYdexxJSCCpWyVwIeci8-7k',
    appId: '1:736732329341:web:b18ddefb264d79b1028814',
    messagingSenderId: '736732329341',
    projectId: 'pixel-bot-cc860',
    authDomain: 'pixel-bot-cc860.firebaseapp.com',
    storageBucket: 'pixel-bot-cc860.firebasestorage.app',
  );
}
