name: GenThinks
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.3.0
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  flutter_image_compress: ^2.1.0
  intl: ^0.19.0
  path: ^1.9.0
  flutter_dotenv: ^5.1.0
  cloudinary_public: ^0.23.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/  # Declare the assets directory (includes all files in assets/)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/GenThinks.png"
  adaptive_icon_background: "#1C1C1E"
  adaptive_icon_foreground: "assets/GenThinks.png"